on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
        image: ghcr.io/psdi-pathfinder4/aiida-testbase:dev
    name: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4

    - name: Start AiiDA with a test profile
      shell: bash
      run: /home/aiida/aiida-start

    - name: Install aiida-gromacs and its testing dependencies
      shell: bash
      run: pip install -e .[testing]

    - name: Run test suite
      shell: bash
      run: pytest --cov aiida_gromacs --cov-report term-missing --cov-append .

    - name: Report Coverage
      uses: coverallsapp/github-action@v2
