name: tests

on:
  repository_dispatch:
    types: [test]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' }}
    name: ${{ matrix.platform }} tests
    timeout-minutes: 30
    steps:
      - name: Test notebooks
        shell: bash
        run: |
          docker run -t ghcr.io/${{ github.repository }}:dev bash -c " \
            pip install pytest nbmake; \
            find . -name '*.ipynb' | pytest --nbmake --nbmake-timeout=3600; "

      - name: Authenticate with GHCR
        id: auth
        uses: docker/login-action@v3.4.0
        with:
          registry: "ghcr.io"
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

  tag-release:
    runs-on: ubuntu-24.04
    needs:
      - tests
    steps:
      - name: Push new tags
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.event.client_payload.tag }} \
            ghcr.io/${{ github.repository }}:dev
