name: tests

on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Testing ${{ github.repository }}
    steps:

    - name: Test notebooks
      shell: bash
      run: |
        docker run -t ghcr.io/${{ github.repository }}:dev bash -c "pip install pytest nbmake; pytest --nbmake *.ipynb;"

    - uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: ${{ github.repository }}
        target: dev
        tags: |
          ${{ github.event.client_payload.tag }}
          latest
