name: tests

on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
        image: ghcr.io/${{ github.repository }}:dev
    name: Testing ${{ github.repository }}
    steps:

    - name: Install testing packages
      shell: bash
      run: pip install pytest nbmake

    - name: Test notebooks
      shell: bash
      run: pytest --nbmake *./ipynb

    - uses: shrink/actions-docker-registry-tag@v4
      with:
        registry: ghcr.io
        repository: ${{ github.repository }}
        target: dev-${{ github.event.client_payload.tag }}
        tags: |
          ${{ github.event.client_payload.tag }}
          latest
